title: FXRadio
email: fxradio@hudacek.online
description: >- # this means to ignore newlines until "baseurl:"
    Free internet radio directory software for Windows, Mac & Linux.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: true
# Build settings
theme: jekyll-theme-cayman

github:
    repository_url: "https://github.com/Joseph5610/fxradio"
    release_url: "https://github.com/Joseph5610/fxradio/releases"
plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
