name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: "Build and create JAR artifact"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          java-package: jdk+fx
      - run: ./gradlew -i jfxJar
        env:
          FX_APPEND_PATH: /zulu-8.jdk/Contents/Home/jre
      - name: Prepare JAR
        run: |
         zip -r releaseJar.zip build/jfx/app/
      - uses: actions/upload-artifact@v2
        with:
          name: fxradio-jar.zip
          path: releaseJar.zip
          if-no-files-found: error
          retention-days: 60
  buildwin:
    name: "Create Windows release"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
              distribution: 'zulu'
              java-version: '8'
              java-package: jdk+fx
        - run: ./gradlew -i jfxNative
        - name: test
          run: |
              dir C:\hostedtoolcache\windows\Java_Zulu_jdk+fx\8.0.345-1\x64\ /s /b
  
