name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build and create artifact"
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          java-package: jdk+fx
      - run: ls -all "$JAVA_HOME$FX_PATH_APPEND"/*/*; ./gradlew -i jfxNative
        env:
         FX_PATH_APPEND: /zulu-8.jdk/
      - name: Prepare JAR files
        run: |
         zip -r releaseJar.zip build/jfx/app/
         ls -all */*
         ls -all build/*/*
      - name: Prepare DMG file
        if: runner.os == 'macOS'
        run: |
         zip -r release_macOS.zip build/jfx/native/FXRadio-*.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: fxradio.jar
          path: releaseJar.zip
          if-no-files-found: error
      - uses: actions/upload-artifact@v2 
        if: runner.os == 'macOS'
        with:
          name: fxradio_macOS
          path: release_macOS.zip
          if-no-files-found: error
  
