name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build:
    name: "Build and create APP file"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          java-package: jdk
      - run: ./gradlew -i jfxNative
      - name: Find zipball on filesystem
        id: find-zipball
        run: echo "ZIPBALL_PATH=$(find . -name "FXRadio-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: FXRadio.zip
          path: ${{ env.ZIPBALL_PATH }}
          if-no-files-found: error
          retention-days: 60

